//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by a fork from the Clean Swift HELM Xcode Templates
//  https://github.com/bolzani/clean-swift-templates

@testable import ___PROJECTNAME___
import XCTest

class ___VARIABLE_sceneName___ViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ___VARIABLE_sceneName___ViewController!
    var window: UIWindow!
    private var outputSpy: OutputSpy!
    private var routerSpy: RouterSpy!

    // MARK: Test lifecycle

    override func setUp() {
    super.setUp()
        window = UIWindow()
        setup___VARIABLE_sceneName___ViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup

    func setup___VARIABLE_sceneName___ViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        outputSpy = OutputSpy()
        routerSpy = RouterSpy()
        sut = (storyboard.instantiateViewController(withIdentifier: "___VARIABLE_sceneName___ViewController") as! ___VARIABLE_sceneName___ViewController)
        sut.output = outputSpy
        sut.router = routerSpy
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}

// MARK: Test doubles

private class OutputSpy: ___VARIABLE_sceneName___ViewControllerOutput {
    
}


@objc private class RouterSpy: NSObject, ___VARIABLE_sceneName___RoutingLogic {
    var dataDestination: ___VARIABLE_sceneName___DataDestination?
}