//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by a fork from the Clean Swift HELM Xcode Templates
//  https://github.com/bolzani/clean-swift-templates

@testable import ___PROJECTNAME___
import XCTest

class ___VARIABLE_sceneName___PresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ___VARIABLE_sceneName___Presenter!
    private var spy: OutputSpy!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setup___VARIABLE_sceneName___Presenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setup___VARIABLE_sceneName___Presenter() {
        spy = OutputSpy()
        sut = ___VARIABLE_sceneName___Presenter(output: spy)
    }

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}

// MARK: - Test Doubles

private class OutputSpy: ___VARIABLE_sceneName___PresenterOutput {
    
}