//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by a fork from the Clean Swift HELM Xcode Templates
//  https://github.com/bolzani/clean-swift-templates

protocol ___VARIABLE_sceneName___InteractorInput: ___VARIABLE_sceneName___ViewControllerOutput {}
protocol ___VARIABLE_sceneName___InteractorOutput {
    
}

protocol ___VARIABLE_sceneName___DataSource: class {
    
}

protocol ___VARIABLE_sceneName___DataDestination: class {
    
}

class ___VARIABLE_sceneName___Interactor {
    
    var output: ___VARIABLE_sceneName___InteractorOutput
    var worker: ___VARIABLE_sceneName___Worker

    init(output: ___VARIABLE_sceneName___InteractorOutput, worker: ___VARIABLE_sceneName___Worker = ___VARIABLE_sceneName___Worker()) {
        self.output = output
        self.worker = worker
    }
    
}

// MARK: - ___VARIABLE_sceneName___InteractorInput

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorInput {

}

// MARK: - ___VARIABLE_sceneName___DataSource

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___DataSource {
    
}

// MARK: - ___VARIABLE_sceneName___DataDestination

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___DataDestination {
    
}