//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by a fork from the Clean Swift HELM Xcode Templates
//  https://github.com/bolzani/clean-swift-templates

protocol ___VARIABLE_sceneName___PresenterInput: ___VARIABLE_sceneName___InteractorOutput {}
protocol ___VARIABLE_sceneName___PresenterOutput: class {
    
}

class ___VARIABLE_sceneName___Presenter {
    
    weak var output: ___VARIABLE_sceneName___PresenterOutput?
    
    init(output: ___VARIABLE_sceneName___PresenterOutput) {
        self.output = output
    }
    
}

// MARK: - ___VARIABLE_sceneName___PresenterInput

extension ___VARIABLE_sceneName___Presenter:___VARIABLE_sceneName___PresenterInput {

}
