//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by a fork from the Clean Swift HELM Xcode Templates
//  https://github.com/bolzani/clean-swift-templates

import UIKit

class ___VARIABLE_sceneName___Configurator {
    
    static let sharedInstance = ___VARIABLE_sceneName___Configurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ___VARIABLE_sceneName___ViewController) {
        
        let presenter = ___VARIABLE_sceneName___Presenter(output: viewController)        
        let interactor = ___VARIABLE_sceneName___Interactor(output: presenter)
        let router = ___VARIABLE_sceneName___Router(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
